/**
 * Lexiom 1.4 — document Realization (POC).
 * Server-side document.md generation + TEXTUAL_SNIPPET evidence.
 * Full browser WebContainer CA remains Phase c (TRH COOP/COEP page).
 * Adapted conceptually from Lexiom 1.3 document_builder outcomes without importing Lexiom_1_3/.
 */
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { emitSessionEvent, provenanceId } from './lexiom14Sessions.js';
import { appendLexiom14ConsumptionEvent } from './lexiom14Metering.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const ARTIFACT_ROOT = path.join(ROOT, 'builds', 'lexiom14');

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function ensureDir(p) {
  fs.mkdirSync(p, { recursive: true });
}

/**
 * @param {object} session
 * @param {object} identity
 */
export async function startDocumentRealization(session, identity) {
  if (!session.build_readiness?.ready) {
    const err = new Error('not_build_ready');
    err.code = 'not_build_ready';
    throw err;
  }
  if (session.realization && session.realization.run_status === 'running') {
    const err = new Error('realization_already_running');
    err.code = 'realization_already_running';
    throw err;
  }

  const realization_id = 'rlz_' + crypto.randomBytes(8).toString('hex');
  const started_at = new Date().toISOString();
  const prov = provenanceId();
  session.realization = {
    realization_id,
    profile: 'document',
    run_status: 'running',
    started_at,
    provenance_id: prov
  };
  session.package = null;

  emitSessionEvent(session.session_id, 'realizationStarted', {
    profile: 'document',
    run_status: 'running'
  });

  // Async pipeline (non-blocking HTTP response returns realization_id first)
  setImmediate(() => {
    runDocumentPipeline(session, identity, realization_id, prov, started_at).catch((e) => {
      session.realization.run_status = 'failed';
      emitSessionEvent(session.session_id, 'realizationFailed', {
        error: {
          code: e.code || 'realization_failed',
          message: e.message || String(e),
          retryable: false
        },
        run_status: 'failed'
      });
    });
  });

  return { realization_id };
}

async function runDocumentPipeline(session, identity, realization_id, prov, started_at) {
  const stepCompose = 'step_compose';
  emitSessionEvent(session.session_id, 'stepStarted', {
    step_id: stepCompose,
    label: 'Compose document from approved intent'
  });
  await sleep(40);
  emitSessionEvent(session.session_id, 'stepProgress', {
    step_id: stepCompose,
    ratio: 0.4,
    message: 'Drafting markdown'
  });

  const osn = session.osn || {};
  const intent =
    String(osn.output_spec || '').trim() ||
    session.structure?.hemispheres?.output_spec_summary ||
    session.case_label ||
    'Lexiom 1.4 document outcome';
  const evidenceHint =
    String(osn.success_evidences?.[0]?.inspection_prompt || '').trim() ||
    session.structure?.hemispheres?.success_evidence_summary ||
    'A readable excerpt from the delivered document';
  const title = String(osn.title || intent.split('\n')[0] || 'Document outcome').trim();

  const docBody = [
    `# ${title.replace(/^Document should realize:\s*/i, '')}`,
    '',
    '## Purpose',
    '',
    String(osn.seed || intent).trim(),
    '',
    '## Output specification',
    '',
    intent,
    '',
    '## Success inspection',
    '',
    evidenceHint,
    '',
    '## Outcome description',
    '',
    ...session.messages
      .filter((m) => m.role === 'user')
      .map((m) => `- ${m.text}`),
    '',
    '---',
    '',
    `_Generated by Lexiom 1.4 document Realization (${realization_id})._`,
    ''
  ].join('\n');

  const dir = path.join(ARTIFACT_ROOT, session.session_id, realization_id);
  ensureDir(dir);
  const docPath = path.join(dir, 'document.md');
  fs.writeFileSync(docPath, docBody, 'utf8');

  const artifact_id = 'art_' + crypto.randomBytes(6).toString('hex');
  const evidence_id = 'ev_' + crypto.randomBytes(6).toString('hex');
  const snippet = docBody.split('\n').slice(0, 8).join('\n');
  const evidencePath = path.join(dir, `${evidence_id}.snippet.md`);
  fs.writeFileSync(evidencePath, snippet, 'utf8');

  emitSessionEvent(session.session_id, 'stepProgress', {
    step_id: stepCompose,
    ratio: 0.8,
    message: 'Writing artifacts'
  });

  const artifact = {
    artifact_id,
    media_kind: 'document',
    content_type: 'text/markdown',
    file_name: 'document.md',
    uri: `/lexiom14/v1/artifacts/${artifact_id}`,
    inline_text: undefined,
    _abs_path: docPath,
    _session_id: session.session_id,
    _realization_id: realization_id
  };

  const evidence = {
    evidence_id,
    kind: 'TEXTUAL_SNIPPET',
    direct: true,
    label: 'Opening of delivered document.md',
    uri: `/lexiom14/v1/evidences/${evidence_id}`,
    inline_text: undefined,
    structure_node_id: 'node_evidence',
    _abs_path: evidencePath,
    _session_id: session.session_id,
    _realization_id: realization_id
  };

  session._artifacts = session._artifacts || new Map();
  session._evidences = session._evidences || new Map();
  session._artifacts.set(artifact_id, artifact);
  session._evidences.set(evidence_id, evidence);

  // Global lookup for GET routes
  registerArtifact(artifact);
  registerEvidence(evidence);

  emitSessionEvent(session.session_id, 'artifactUpdated', {
    artifact: publicArtifact(artifact)
  });
  emitSessionEvent(session.session_id, 'evidenceProduced', {
    evidence: publicEvidence(evidence)
  });
  emitSessionEvent(session.session_id, 'stepCompleted', { step_id: stepCompose });

  const meter = appendLexiom14ConsumptionEvent({
    service: 'lexiom14.realization.document',
    session_id: session.session_id,
    vertical_id: identity?.vertical_id,
    tenant_pseudonym: identity?.tenant_pseudonym,
    app_id: identity?.app_id,
    env: identity?.env,
    actor_pseudonym: identity?.actor_pseudonym,
    provenance_id: prov,
    measurement: { unit: 'realization', quantity: 1 }
  });

  const completed_at = new Date().toISOString();
  const pkg = {
    package_id: 'rp_' + crypto.randomBytes(6).toString('hex'),
    status: 'completed',
    profile: 'document',
    artifact: publicArtifact(artifact),
    success_evidences: [publicEvidence(evidence)],
    provenance: {
      provenance_id: prov,
      session_id: session.session_id,
      profile: 'document',
      started_at,
      completed_at,
      agent_label: 'lexiom14-document-poc'
    },
    metering_ids: [meter.event_id],
    structure_revision: session.structure.revision
  };

  session.package = pkg;
  session.realization.run_status = 'completed';
  session.realization.completed_at = completed_at;

  emitSessionEvent(session.session_id, 'realizationCompleted', { package: pkg });
}

/** @type {Map<string, object>} */
const artifactIndex = new Map();
/** @type {Map<string, object>} */
const evidenceIndex = new Map();

function registerArtifact(a) {
  artifactIndex.set(a.artifact_id, a);
}
function registerEvidence(e) {
  evidenceIndex.set(e.evidence_id, e);
}

export function getArtifactRecord(id) {
  return artifactIndex.get(id) || null;
}
export function getEvidenceRecord(id) {
  return evidenceIndex.get(id) || null;
}

function publicArtifact(a) {
  return {
    artifact_id: a.artifact_id,
    media_kind: a.media_kind,
    content_type: a.content_type,
    file_name: a.file_name,
    uri: a.uri
  };
}

function publicEvidence(e) {
  return {
    evidence_id: e.evidence_id,
    kind: e.kind,
    direct: e.direct,
    label: e.label,
    uri: e.uri,
    structure_node_id: e.structure_node_id
  };
}
